import type { CardCatalog, CardDTO } from "@yugioh-app/contracts";

// ---------------------------------------------------------------------------
// Fixture catalog — used when packages/card-data/out/edison-card-catalog.json
// is not yet present. Contains a representative set of Edison cards sufficient
// to exercise every validator and codec code path.
// ---------------------------------------------------------------------------

// Harpie Lady (base) and Harpie Lady 1 (alias) — same card for copy counting
const HARPIE_LADY_BASE = 76812113; // Harpie Lady
const HARPIE_LADY_ALT = 91932350; // Harpie Lady 1 (aliasOf → HARPIE_LADY_BASE)

export const FIXTURE_CARDS: CardDTO[] = [
  // --- Forbidden ---
  {
    passcode: 99267150,
    name: "Chaos Emperor Dragon - Envoy of the End",
    frame: "effect",
    isExtraDeck: false,
    race: "Dragon",
    attribute: "DARK",
    level: 8,
    atk: 3000,
    def: 2500,
    desc: "Cannot be Normal Summoned/Set. Must be Special Summoned…",
    banlist: "forbidden",
    aliasOf: null,
    imageId: 99267150,
  },
  // --- Limited (1 copy) ---
  {
    passcode: 24094653,
    name: "Black Luster Soldier - Envoy of the Beginning",
    frame: "effect",
    isExtraDeck: false,
    race: "Warrior",
    attribute: "LIGHT",
    level: 8,
    atk: 3000,
    def: 2500,
    desc: "Cannot be Normal Summoned/Set. Must be Special Summoned…",
    banlist: "limited",
    aliasOf: null,
    imageId: 24094653,
  },
  // --- Semi-Limited (2 copies) ---
  {
    passcode: 12538374,
    name: "Treeborn Frog",
    frame: "effect",
    isExtraDeck: false,
    race: "Aqua",
    attribute: "WATER",
    level: 1,
    atk: 100,
    def: 100,
    desc: "During your Standby Phase…",
    banlist: "semi",
    aliasOf: null,
    imageId: 12538374,
  },
  // --- Unlimited monsters ---
  {
    passcode: 89631139,
    name: "Beast King Barbaros",
    frame: "effect",
    isExtraDeck: false,
    race: "Beast-Warrior",
    attribute: "EARTH",
    level: 8,
    atk: 3000,
    def: 1200,
    desc: "You can Normal Summon this card without Tributing…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 89631139,
  },
  {
    passcode: 46986414,
    name: "Cyber Dragon",
    frame: "effect",
    isExtraDeck: false,
    race: "Machine",
    attribute: "LIGHT",
    level: 5,
    atk: 2100,
    def: 1600,
    desc: "If your opponent controls a monster and you control no monsters…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 46986414,
  },
  {
    passcode: 70781052,
    name: "Dark Armed Dragon",
    frame: "effect",
    isExtraDeck: false,
    race: "Dragon",
    attribute: "DARK",
    level: 7,
    atk: 2800,
    def: 1000,
    desc: "Cannot be Normal Summoned/Set. Must be Special Summoned…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 70781052,
  },
  // --- Ritual monster (goes in Main Deck) ---
  {
    passcode: 5405694,
    name: "Black Luster Soldier",
    frame: "ritual",
    isExtraDeck: false,
    race: "Warrior",
    attribute: "EARTH",
    level: 8,
    atk: 3000,
    def: 2500,
    desc: "This card can only be Ritual Summoned with the Ritual Spell…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 5405694,
  },
  // --- Fusion monster (goes in Extra Deck) ---
  {
    passcode: 35809262,
    name: "Elemental HERO Flame Wingman",
    frame: "fusion",
    isExtraDeck: true,
    race: "Warrior",
    attribute: "WIND",
    level: 6,
    atk: 2100,
    def: 1200,
    desc: '"Elemental HERO Avian" + "Elemental HERO Burstinatrix"…',
    banlist: "unlimited",
    aliasOf: null,
    imageId: 35809262,
  },
  // --- Synchro monster (goes in Extra Deck) ---
  {
    passcode: 67959180,
    name: "Goyo Guardian",
    frame: "synchro",
    isExtraDeck: true,
    race: "Warrior",
    attribute: "EARTH",
    level: 6,
    atk: 2800,
    def: 2000,
    desc: "1 Tuner + 1 or more non-Tuner monsters…",
    banlist: "limited",
    aliasOf: null,
    imageId: 67959180,
  },
  // --- Spell ---
  {
    passcode: 55144522,
    name: "Pot of Greed",
    frame: "spell",
    isExtraDeck: false,
    race: "Normal",
    attribute: null,
    level: null,
    atk: null,
    def: null,
    desc: "Draw 2 cards.",
    banlist: "forbidden",
    aliasOf: null,
    imageId: 55144522,
  },
  // --- Trap ---
  {
    passcode: 29401950,
    name: "Bottomless Trap Hole",
    frame: "trap",
    isExtraDeck: false,
    race: "Normal",
    attribute: null,
    level: null,
    atk: null,
    def: null,
    desc: "When your opponent Summons a monster(s) with 1500 or more ATK…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 29401950,
  },
  // --- Additional unlimited monsters (needed for 40-card legal main in tests) ---
  {
    passcode: 71413901,
    name: "Breaker the Magical Warrior",
    frame: "effect",
    isExtraDeck: false,
    race: "Spellcaster",
    attribute: "DARK",
    level: 4,
    atk: 1600,
    def: 1000,
    desc: "When this card is Normal Summoned, place 1 Spell Counter on it.",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 71413901,
  },
  {
    passcode: 28604635,
    name: "Snipe Hunter",
    frame: "effect",
    isExtraDeck: false,
    race: "Fiend",
    attribute: "DARK",
    level: 4,
    atk: 1500,
    def: 600,
    desc: "You can discard 1 card to target 1 card on the field…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 28604635,
  },
  {
    passcode: 83011277,
    name: "Mystic Tomato",
    frame: "effect",
    isExtraDeck: false,
    race: "Plant",
    attribute: "DARK",
    level: 4,
    atk: 1400,
    def: 1100,
    desc: "When this card is destroyed by battle…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 83011277,
  },
  {
    passcode: 23205979,
    name: "Spirit Reaper",
    frame: "effect",
    isExtraDeck: false,
    race: "Zombie",
    attribute: "DARK",
    level: 3,
    atk: 300,
    def: 200,
    desc: "This card cannot be destroyed by battle.",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 23205979,
  },
  {
    passcode: 71564252,
    name: "Thunder King Rai-Oh",
    frame: "effect",
    isExtraDeck: false,
    race: "Thunder",
    attribute: "LIGHT",
    level: 4,
    atk: 1900,
    def: 800,
    desc: "Neither player can add cards from their Deck to their hand except by drawing them.",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 71564252,
  },
  {
    passcode: 24508238,
    name: "D.D. Crow",
    frame: "effect",
    isExtraDeck: false,
    race: "Winged Beast",
    attribute: "DARK",
    level: 1,
    atk: 100,
    def: 100,
    desc: "You can discard this card to the Graveyard to remove from play 1 card…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 24508238,
  },
  {
    passcode: 80441106,
    name: "Neo-Spacian Grand Mole",
    frame: "effect",
    isExtraDeck: false,
    race: "Rock",
    attribute: "EARTH",
    level: 1,
    atk: 900,
    def: 300,
    desc: "At the start of the Damage Step, if this card battles an opponent's monster…",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 80441106,
  },
  {
    passcode: 7572887,
    name: "D.D. Warrior Lady",
    frame: "effect",
    isExtraDeck: false,
    race: "Warrior",
    attribute: "LIGHT",
    level: 4,
    atk: 1500,
    def: 1600,
    desc: "When this card battles another monster, after damage calculation you can remove both from play.",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 7572887,
  },
  {
    passcode: 89943723,
    name: "Elemental HERO Neos",
    frame: "effect",
    isExtraDeck: false,
    race: "Warrior",
    attribute: "LIGHT",
    level: 7,
    atk: 2500,
    def: 2000,
    desc: "An E HERO who arrived from Neo-Space.",
    banlist: "unlimited",
    aliasOf: null,
    imageId: 89943723,
  },
  // --- Alt-art alias pair: Harpie Lady (base) ---
  {
    passcode: HARPIE_LADY_BASE,
    name: "Harpie Lady",
    frame: "effect",
    isExtraDeck: false,
    race: "Winged Beast",
    attribute: "WIND",
    level: 4,
    atk: 1300,
    def: 1400,
    desc: "All WIND monsters gain 300 ATK while this card is on the field.",
    banlist: "unlimited",
    aliasOf: null,
    imageId: HARPIE_LADY_BASE,
  },
  // --- Alt-art alias: Harpie Lady 1 counts as Harpie Lady ---
  {
    passcode: HARPIE_LADY_ALT,
    name: "Harpie Lady 1",
    frame: "effect",
    isExtraDeck: false,
    race: "Winged Beast",
    attribute: "WIND",
    level: 4,
    atk: 1300,
    def: 1400,
    desc: "This card's name is always treated as Harpie Lady…",
    banlist: "unlimited",
    aliasOf: HARPIE_LADY_BASE,
    imageId: HARPIE_LADY_BASE,
  },
];

export const FIXTURE_CATALOG: CardCatalog = {
  format: "edison-2010-03",
  generatedAt: "2026-07-13T00:00:00.000Z",
  count: FIXTURE_CARDS.length,
  cards: FIXTURE_CARDS,
};
